# Generated by Django 3.1.5 on 2021-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='Rut de usuario')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Cuenta de usuario')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=100, unique=True, verbose_name='Correo electronico')),
                ('estado', models.BooleanField(default=True)),
                ('user_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
