# Generated by Django 3.1.5 on 2021-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha creación'),
        ),
    ]
