# Generated by Django 3.1.5 on 2021-02-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210204_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_administrador',
            field=models.BooleanField(default=False, verbose_name='Usuario Administrador'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cuenta Usuario'),
        ),
    ]
